---

# operate on the group and ensure that its state is accurate"

- name: "Ensure state for group {{ group.name }}"
  redhat.rhel_idm.ipagroup:
    action: "{{ group.action | default(omit) }}"
    ipaadmin_principal: "{{ ipa_admin_principal }}"
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: "{{ group.name }}"
    description: "{{ group.description | default(omit) }}"
    state: "{{ group.state | default('present') }}"
    external: "{{ group.external | default(omit) }}"
    gid: "{{ group.gid | default(omit) }}"
    group: "{{ group.group_list | default(omit) }}"
    groups: "{{ group.group_dict | default(omit) }}"
    membermanager_group: "{{ group.membermanager_groups | default(omit) }}"
    membermanager_user: "{{ group.membermanager_users | default(omit) }}"
    posix: "{{ group.posix | default(omit) }}"
    rename: "{{ group.rename | default(omit) }}"
    user: "{{ group.user_list | default(omit) }}"
