---

# on RHEL 7 fail
# on RHEL 8 reset the module and install
# on RHEL 9++ just dnf install
- name: "Check OS minimum version"
  ansible.builtin.assert:
    that: (ansible_distribution_major_version | int) > 7
    fail_msg: "Deployment on RHEL 7 or lower is no longer supported"

- name: "If RHEL8, configure the modular components for installation"
  when: (ansible_distribution_major_version | int) == 8
  block:

    - name: "Reset the IdM Module"
      ansible.builtin.command: "dnf module reset idm"
      changed_when: true

    - name: "Enable the IdM Module"
      ansible.builtin.command: "dnf module enable idm:DL1"
      changed_when: true

    - name: "Perform a modular install of packages"
      ansible.builtin.command: "dnf module install idm:DL1/{adtrust,client,common,dns,server}"
      changed_when: true

- name: "Install the components"
  when: (ansible_distribution_major_version | int) > 8
  block:

    - name: "Install IdM packages"
      ansible.builtin.dnf:
        name:
          - ipa-server
          - ipa-server-dns
          - ipa-server-trust-ad
          - ipa-healthcheck

- name: "Install the SOS Report package"
  ansible.builtin.dnf:
    name: sos
    state: present
