---

# run the hbactest command
- name: "Log test parameters"
  ansible.builtin.debug:
    var: hbactest

# There is no module to implement this. We will do it through the API using the CLI
- name: "Create the payload --user="
  ansible.builtin.set_fact:
    payload: 'ipa hbactest --user={{ hbactest.user }}'

- name: "Create the payload --host="
  ansible.builtin.set_fact:
    payload: '{{ payload }} --host={{ hbactest.host }}'

- name: "Create the payload --service="
  ansible.builtin.set_fact:
    payload: '{{ payload }} --service={{ hbactest.service }}'

- name: "Create the payload --service="
  when: hbactest.rules is defined
  ansible.builtin.set_fact:
    payload: '{{ payload }} --rules={{ rule }}'
  loop: "{{ hbactest.rules }}"
  loop_control:
    loop_var: rule
