---

# ensure the state of a sudo command.
- name: "Ensure the state of a sudo command."
  redhat.rhel_idm.ipasudocmd:
    ipaadmin_principal: "{{ ipa_admin_principal }}"
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: "{{ command.name }}"
    description: "{{ command.description }}"
    state: "{{ command.state | default(omit) }}"
